name: run-performance-tests

on:
  pull_request:
    types: [ labeled ]

jobs:
  test:
    runs-on: ubuntu-22.04
    if: ${{ github.event.label.name == 'Run Performance Tests' }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_ISSUE_NUMBER: ${{ github.event.pull_request.number }}
      GITHUB_ORG: ${{ github.repository_owner }}
      GITHUB_REPO: ${{ github.repository }}
    steps:
      - name: ci/checkout-repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: ci/test
        uses: ./.github/actions/test
